---
title: "Replot the lefse plots with ggplot"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(grid)
library(cowplot)
library(ggpubr)
```

Replot the lefse plots with ggplot2 (with each class + subclass combi)

## Combine and clean the res table from lefse

```{r}
# the input : lefse res files
fns <- list.files('../data/lefse_input/', pattern = 'pathway_abundace_pheno__[CR|Toxicity].+res$', full.names = T)

fns_name <- list.files('../data/lefse_input/', pattern = 'pathway_abundace_pheno__[CR|Toxicity].+res$')

# join all of the tables feature together
feature <- fns %>% 
  set_names(fns_name) %>% 
  map(~ read_tsv(., col_names = c('pathway','xx','direction','score','pval')) %>% 
        filter(!is.na(score))) %>% 
  bind_rows(.id = 'group') %>% 
  mutate(group = str_replace(group, 'pathway_abundace_pheno__','')) %>% 
  mutate(group = str_replace(group, '.res$','')) %>% 
  mutate(pathway = str_replace_all(pathway, '^f_','')) %>% 
  select(-xx, -pval)

# change the "N" direction to be minus score
feature <- bind_rows(
  feature %>% 
    split(.$direction) %>% 
    pluck('N') %>% 
    mutate(score = -score),
  feature %>% 
    split(.$direction) %>% 
    pluck('Y') 
) %>% 
  arrange(group, pathway, score)
```

```{r}
# output the sig unique pathway from the above table for later use in the bar plot
feature  %>% 
  distinct(pathway) %>% 
  write_csv('../data/unique_sig_pathway.csv')
```


## Recreate the lefse figure with ggplot

Each combi per figure

```{r}
feature %>% 
  filter(str_detect(group, pattern = 'Disease_Class$')) %>% 
  split(.$group) %>% 
  map(~  ggplot(data = ., aes(x = reorder(pathway, score), y = score, fill = direction)) +
            geom_bar(position = position_dodge2(preserve = "single"), stat = 'identity') +
            coord_flip() +
            scale_color_manual(values = c('#00468B', '#EC0000'))  +
            scale_fill_manual(values = c('#00468B', '#EC0000')) +
            theme_minimal() +
            theme(axis.title.y  = element_blank(), 
                  legend.position="bottom") +
            labs(title = str_glue('Response to class') ,
                 y = 'Score')+ 
            ggsave(str_glue('/Volumes/castoricenter/CAR-Tcell_and_Microbiota/humann2_shotgun/figs/lefse_results_ggplot_recreate/Response to class {.$group}.pdf'), device = 'pdf', width = 15, dpi = 300))
 
```

```{r}
CR <- feature %>% 
  filter(group == 'CR__Disease_Class') %>% 
  ggplot(aes(x = reorder(pathway, score), y = score, fill = direction)) +
            geom_bar(position = position_dodge2(preserve = "single"), stat = 'identity') +
            coord_flip() +
            scale_color_manual(values = c('#ED0000', '#00468B'))  +
            scale_fill_manual(values = c('#ED0000', '#00468B')) +
            theme_minimal() +
            theme(axis.title.y  = element_blank(), 
                  legend.position="bottom") +
            labs(title = str_glue('Response to Complete Response') ,
                 y = 'Score')+ 
            ylim(-4,4) +
            ggsave(str_glue('/Volumes/castoricenter/CAR-Tcell_and_Microbiota/humann2_shotgun/figs/lefse_results_ggplot_recreate/Response to CR.jpg'),  width = 12, dpi = 300 )

tox <- feature %>% 
  filter(group == 'Toxicity__Disease_Class') %>% 
  ggplot(aes(x = reorder(pathway, score), y = score, fill = direction)) +
            geom_bar(position = position_dodge2(preserve = "single"), stat = 'identity') +
            coord_flip() +
            scale_color_manual(values = c('#0099B4', '#AD002A'))  +
            scale_fill_manual(values = c('#0099B4', '#AD002A')) +
            theme_minimal() +
            theme(axis.title.y  = element_blank(), 
                  legend.position="bottom") +
            labs(title = str_glue('Response to Toxicity') ,
                 y = 'Score')+ 
            ylim(-4,4) +
            ggsave(str_glue('/Volumes/castoricenter/CAR-Tcell_and_Microbiota/humann2_shotgun/figs/lefse_results_ggplot_recreate/Response to tox.jpg'),  width = 12, dpi = 300, height = 3.5)


```



