---
title: "RF to find the top important features"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(randomForest)
```

```{r}
# the species table from metaphlan2
# the species abundance here are actually in percent
s_tb <- read_tsv('../data/metaphlan2_result/merged_abundance_table_species.txt') %>% 
  rename_all(funs(str_replace(., '_profile$','')))

s_tb_sum <- s_tb %>% 
  column_to_rownames('ID') %>% 
  as.matrix() %>% 
  apply(., 2, sum)

# load the pheno
pheno <- read_csv('../data/cleaned_pheno/final_pheno.csv') %>% 
  select(-CAR_Group, -Censor_reason ) 

# to rearrange the cts table 
s_tb <- bind_cols(s_tb[,1],s_tb[,pheno$Sampleid]) 

all.equal(colnames(s_tb)[2:ncol(s_tb)], pheno$Sampleid)
```

```{r}
# to put the feature table in the sample as rowname format to do the ML 
s_tb_rf <- s_tb %>% 
  column_to_rownames('ID') %>% 
  as.matrix() %>% 
  t

# check the sample name really match
all.equal(rownames(s_tb_rf), pheno$Sampleid)

tox_RF <- randomForest(s_tb_rf, factor(pheno$Toxicity), importance = T)

impor_feature <- importance(tox_RF) %>% 
  as.data.frame() %>% 
  rownames_to_column(var = 'species') %>% 
  arrange(MeanDecreaseAccuracy)
```

Although Clostridium innocuum are often present and harmless in healthy people, they have been isolated in various infections and predominantly in patients that are immunocompromised as an opportunistic bacteria.

```{r}
CR_RF <- randomForest(s_tb_rf, factor(pheno$CR), importance = T)

impor_feature <- importance(CR_RF) %>% 
  as.data.frame() %>% 
  rownames_to_column(var = 'species') %>% 
  arrange(MeanDecreaseAccuracy)
```

```{r}
# the pathway abundance table
pabun <- read_tsv('../data/humann2_res/humann2_final_out/humann2_pathabundance_cpm_unstratified.tsv') %>% 
  rename(pathway = names(.)[1]) %>% 
  rename_all(funs(str_replace(., '_Abundance$',''))) %>% 
  # remove the unmapped and the unintegrated record
  filter(!pathway %in% c('UNMAPPED','UNINTEGRATED'))

pabun <- bind_cols(pabun[,1],pabun[,pheno$Sampleid]) 

pabun_rf <- pabun %>% 
  column_to_rownames('pathway') %>% 
  as.matrix() %>% 
  t

all.equal(rownames(pabun_rf), pheno$Sampleid)

tox_RF_PW <- randomForest(pabun_rf, factor(pheno$Toxicity), importance = T)

impor_pw <- importance(tox_RF_PW) %>% 
  as.data.frame() %>% 
  rownames_to_column(var = 'pathway') %>% 
  arrange(MeanDecreaseAccuracy)
```

