---
title: "MaAsLin2 species"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Maaslin2)
```

```{r}
# format the whole table column and keep the samples in the final cohort 33
have_sg <- read_csv('../data/baselinesforAngel10032019.csv') %>% 
  filter(shotgun_YN == 'yes') %>% 
  # removig 1943A cuz its low quality
  filter(sample_id != '1943A') %>% 
  ### FUCK THIS TABLE OF ../data/baselinesforAngel10032019.csv IS WRONG IN 161, it didn’t pass QC because not enough DNA material was present. SO WE DON'T HAVE THE SHOTGUN DATA.
  filter(!sample_id %in% c('161'))

phe_M <- read_excel('/Volumes/castoricenter/CAR-Tcell_and_Microbiota/CTC Event Table 11252019 wo Censor .xlsx',
                    sheet = 5) %>% 
  rename_all(funs(str_replace_all(., ' \\(.+$','') %>% 
    str_replace_all(., ' ','_') %>% 
    str_replace(., ':|-','_'))) %>% 
  filter(is.na(Censor_reason)) %>% 
  filter(Baseline_Sample_ID %in% have_sg$sample_id)

```

```{r}
pheno <- phe_M %>% 
  dplyr::select(sampleid = Baseline_Sample_ID,
                CR, 
                #ORR, 
                Toxicity, 
                Cytokine_Release_Syndrome,   
                ICANS,
                Antibiotics_4_weeks_prior_to_CAR_T_cells,
                #Antibiotics_4_weeks_post_CAR_T_cells,
                Disease_Class,
                Key__Patient_Disease_Status_at_CAR
                ) %>% 
  # change all the pheno vars to factors
  mutate_if(is.character, as.factor) %>% 
  column_to_rownames('sampleid') 
```


```{r}
spp <- read_tsv('../data/metaphlan2_result/merged_abundance_table_genus.txt') %>% 
  dplyr::rename_all(funs(str_replace(., '_profile$',''))) %>% 
  dplyr::rename(spp = names(.)[1])  %>% 
  column_to_rownames('spp') %>% 
  as.matrix() %>% 
  t() %>% 
  as.data.frame()

fit_data <- Maaslin2(
    spp, pheno, '../data/maASlin2/genus', normalization  = 'NONE', transform = "AST",  cores = 4, plot_heatmap = F,
    standardize = FALSE)
```