---
title: "rethinking and the 5 genera"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

```{r}
library(rethinking)
library(tidyverse)  
library(ggpubr)
set.seed(123)
```

# CR/Toxicity ~ Akkermansia + Bacteroides + Enterococcus + Faecalibacterium + Ruminococcus + center

## Toxicity

```{r}
genera <- read_csv('../data/amplicon/stool/combined_5_genera.csv')

# do not standardize the log transformed relative abundance 
meta <- read_csv('../data/amplicon/stool/combined_2_meta_expanded.csv')  %>% 
  inner_join(genera)

# wanna see the range of the 5 genera log 10 relab
meta %>% select(Akkermansia:Ruminococcus) %>% 
  summary
```


```{r}
set.seed(123)   
dat_list <- list(
    tox = meta$tox,
    cr100 = meta$cr100,
    location = meta$loca,
    Akkermansia = meta$Akkermansia,
    Bacteroides = meta$Bacteroides,
    Enterococcus = meta$Enterococcus,
    Faecalibacterium = meta$Faecalibacterium,
    Ruminococcus = meta$Ruminococcus
    ) 
```

```{r}
gtox <- ulam(
    alist(
        tox ~ dbinom( 1 , p ) ,
        logit(p) <- ba*Akkermansia + bb*Bacteroides + be*Enterococcus + bf*Faecalibacterium + br*Ruminococcus + a[location] ,
        ba ~ dnorm( 0 , 1),
        bb ~ dnorm( 0 , 1),
        be ~ dnorm( 0 , 1),
        bf ~ dnorm( 0 , 1),
        br ~ dnorm( 0 , 1),
        a[location] ~ dnorm( 0 , 0.5 )
    ) , data=dat_list , chains=4 , log_lik=TRUE , cores = 16)
precis(gtox, prob = 0.95)   
plot(precis(gtox, depth = 2, prob = 0.95) , pars = c('ba','bb','be','bf','br'), labels = c('Akkermansia', 'Bacteroides','Enterococcus','Faecalibacterium','Ruminococcus'))  
# indicative of the Bacteroides link with toxicity  
```
   
```{r}
# make this plot myself with a pre-defined range in the axis
df <- precis(gtox,  prob = 0.95)  %>% as.tibble()
df <- df %>%
  mutate(variable = c('Akkermansia', 'Bacteroides','Enterococcus','Faecalibacterium','Ruminococcus'))

#remove row number 1 (The intercept)
df %>% 
  ggplot(aes(x = variable, y = mean)) +
  geom_point(shape = 15,
             size  = 4, width = 0.1,
             position = "dodge", color="black") +
  geom_errorbar(aes(ymin  = `2.5%`,
                    ymax  = `97.5%`),
                width = 0.1,
                size  = 0.7,
                position = "dodge", color="turquoise4") +
  theme(axis.title = element_text(face = "bold")) +
  xlab("Variables") + ylab("Coefficient with 95% CI") +
  coord_flip(ylim = c(-1.5, 1.5)) +
  geom_hline(yintercept = 0, color = "red", size = 1) +
   theme(axis.title = element_text(size = 0)) +
  theme(axis.text = element_text(size = 14)) +
  labs(title = 'Toxicity') +
  ggsave('../figs/amplicon/bayesian_genera_tox_log10.pdf', width = 5, height = 4)
```
   
   
```{r}
post <- extract.samples(gtox) 
meta_ <- meta %>% 
  select(Akkermansia:Ruminococcus)

# the post coeffs in df format
postdf <- bind_cols(ba = post$ba, bb = post$bb, be = post$be, bf = post$bf, br = post$br, am = post$a[,1])

N <- 100
# for the top and bottom quantile range of Bacteroides relab
ba_top <- meta_ %>% 
  filter(Bacteroides >= quantile(meta$Bacteroides, 0.9))
ba_bot <- meta_ %>% 
  filter(Bacteroides <= quantile(meta$Bacteroides, 0.1))

per_pt_sample_post_prob <- function(lga_, lgb_, lge_, lgf_ , lgr_){
  # the input is the log relab of the 5 genera for that patient
  post_samp <- postdf %>% 
    sample_n(size = N, replace = F)
  
  ret = pmap(post_samp, function(ba, bb, be, bf, br, am) {
    inv_logit( ba * lga_ + bb * lgb_ + be * lge_ +  bf * lgf_ + br * lgr_ + am ) 
  }) %>% 
    set_names(seq(1, N)) %>% 
    bind_rows() %>% 
    gather()
  return(ret)
}

# for the top quantile patients 
res_top <- pmap(ba_top, function(Akkermansia, Bacteroides, Enterococcus, Faecalibacterium, Ruminococcus){
  per_pt_sample_post_prob(Akkermansia, Bacteroides, Enterococcus, Faecalibacterium, Ruminococcus)
}) %>% 
  set_names(paste('P', seq(1, nrow(ba_top)), sep = '')) %>% 
  bind_rows(.id = 'pt')

# for the bottom quantile patients  
res_bot <- pmap(ba_bot, function(Akkermansia, Bacteroides, Enterococcus, Faecalibacterium, Ruminococcus){
  per_pt_sample_post_prob(Akkermansia, Bacteroides, Enterococcus, Faecalibacterium, Ruminococcus)
}) %>% 
  set_names(paste('P', seq(1, nrow(ba_bot)), sep = '')) %>% 
  bind_rows(.id = 'pt')   

# plot them together in one 
bind_rows(
  res_top %>% mutate(grp = 'top'),
  res_bot %>% mutate(grp = 'bot')
) %>% 
  gghistogram(x = 'value',bins = 30, fill = 'grp', palette = 'nejm', color = 'white', add = 'mean',
                  xlab = 'Predicted probability of Toxicity', ylab = 'Probability density') +
  ggsave('../figs/predicted_tox_bacteroides_top_bottom_10.pdf', width = 7, height = 5)

bind_rows(
  res_top %>% mutate(grp = 'top'),
  res_bot %>% mutate(grp = 'bot')
) %>% 
  group_by(grp) %>% 
  summarise(ave = mean(value))


```

### posterior check 

```{r}
post <- extract.samples(gtox) 
# using the patient with highest and lowest Bacteroides data to plug in
# find the patients
bl <- meta %>% 
  arrange(Bacteroides) %>% 
  slice(1) %>% 
  select(Akkermansia:Ruminococcus)

bh <- meta %>% 
  arrange(-Bacteroides) %>% 
  slice(1) %>% 
  select(Akkermansia:Ruminococcus)


pl <- inv_logit( post$ba * (-1.612806	) + post$bb * (-5.69897		) + post$be * (-5.69897	) +  post$bf * (-5.69897		) + post$br * (-0.5244935) + post$a[, 1] ) 

ph <- inv_logit( post$ba * (-2.286752	) + post$bb * (-0.4575058) + post$be * (-1.745601	) +  post$bf * (-5.69897) + post$br * (-4.050354) + post$a[, 1] )


bind_rows(
  tibble(
    value = pl,
    grp = 'low'
  ),
  tibble( 
    value = ph,
    grp = 'high'
  )
) %>% 
  gghistogram(x = 'value',bins = 30, fill = 'grp', palette = 'nejm', color = 'white',add = 'mean',title = 'MSK',
              xlab = 'Predicted probability of toxicity', ylab = 'Probability density')
  
bind_rows(
  tibble(value = pl,grp = 'low'),
  tibble( value = ph,grp = 'high')
)   %>% 
  group_by(grp) %>% 
  summarise(m = mean(value))
```


## CR

```{r}
gcr <- ulam(
    alist(
        cr100 ~ dbinom( 1 , p ) ,
        logit(p) <- ba*Akkermansia + bb*Bacteroides + be*Enterococcus + bf*Faecalibacterium + br*Ruminococcus + a[location] ,
        ba ~ dnorm( 0 , 1),
        bb ~ dnorm( 0 , 1),
        be ~ dnorm( 0 , 1),
        bf ~ dnorm( 0 , 1),
        br ~ dnorm( 0 , 1),
        a[location] ~ dnorm( 0 , 0.5 )
    ) , data=dat_list , chains=4 , log_lik=TRUE , cores = 8)
precis(gcr, prob = 0.95) 
plot(precis(gcr, depth = 2, prob = 0.95) ) 
# I think the Ruminococcus still holds for the CR
```

```{r}
# make this plot myself with a pre-defined range in the axis
df <- precis(gcr,  prob = 0.95)  %>% as.tibble()
df <- df %>%
  mutate(variable = c('Akkermansia', 'Bacteroides','Enterococcus','Faecalibacterium','Ruminococcus'))

#remove row number 1 (The intercept)
df %>% 
  ggplot(aes(x = variable, y = mean)) +
  geom_point(shape = 15,
             size  = 4, width = 0.1,
             position = "dodge", color="black") +
  geom_errorbar(aes(ymin  = `2.5%`,
                    ymax  = `97.5%`),
                width = 0.1,
                size  = 0.7,
                position = "dodge", color="turquoise4") +
  theme(axis.title = element_text(face = "bold")) +
  xlab("Variables") + ylab("Coefficient with 95% CI") +
  coord_flip(ylim = c(-1.5, 1.5)) +
  geom_hline(yintercept = 0, color = "red", size = 1) +
   theme(axis.title = element_text(size = 0)) +
  theme(axis.text = element_text(size = 14)) +
  labs(title = 'CR') +
  ggsave('../figs/amplicon/bayesian_genera_cr_log10.pdf', width = 5, height = 4)
```


### posterior check 


```{r}
post <- extract.samples(gcr) 
# using the patient with highest and lowest Ruminococcus data to plug in
# find the patients
rl <- meta %>% 
  arrange(Ruminococcus) %>% 
  slice(1) %>% 
  select(Akkermansia:Ruminococcus)

rh <- meta %>% 
  arrange(-Ruminococcus) %>% 
  slice(1) %>% 
  select(Akkermansia:Ruminococcus)

pl <- inv_logit( post$ba * (-3.517128) + post$bb * (-2.447201	) + post$be * (-2.504205	) +  post$bf * (-5.69897	) + post$br * (-5.69897) + post$a[, 1] ) 

ph <- inv_logit( post$ba * (-1.845325	) + post$bb * (-3.052386) + post$be * (-5.69897) +  post$bf * (-5.69897) + post$br * (-0.373353) + post$a[, 1] )

bind_rows(
  tibble(value = pl,grp = 'low'),
  tibble( value = ph,grp = 'high')
) %>% 
  gghistogram(x = 'value',bins = 30, fill = 'grp', palette = 'nejm', color = 'white',title = 'MSK', add = 'mean',
              xlab = 'Predicted probability of CR d100', ylab = 'Probability density')


bind_rows(
  tibble(value = pl,grp = 'low'),
  tibble( value = ph,grp = 'high')
)   %>% 
  group_by(grp) %>% 
  summarise(m = mean(value))
```

```{r}
# ruminococcus relab quantile
meta_ <- meta %>% 
  select(Akkermansia:Ruminococcus)

# the post coeffs in df format
postdf <- bind_cols(ba = post$ba, bb = post$bb, be = post$be, bf = post$bf, br = post$br, am = post$a[,1])

# to responde to Sean's comments to not use max and min "extreme"patient data
# use the 90% and 10% quantile patient data
# Jonas: how do you know that the patient falling onto the 90%tile is not “exceptional” and therefore an “outlier” in another feature that your model includes, besides ruminococcus, he suggests to sample in that 0-10% quantile range patient data for example
# It is 100 jointly sampled coefficients multiplied with the composition of bacteria in the current patient
N <- 100
# for the top and bottom quantile range of ruminococcus relab
ru_top <- meta_ %>% 
  filter(Ruminococcus >= quantile(meta$Ruminococcus, 0.9))
ru_bot <- meta_ %>% 
  filter(Ruminococcus <= quantile(meta$Ruminococcus, 0.1))

# sample in the top and bot patients 100 times
ru_top_samp <- ru_top %>% 
    sample_n(size = N, replace = T)
ru_bot_samp <- ru_bot %>% 
    sample_n(size = N, replace = T)

# a function for every patient data generate 100 post prob of CR (sampling from the post 100 times)

per_pt_sample_post_prob <- function(lga_, lgb_, lge_, lgf_ , lgr_){
  # the input is the log relab of the 5 genera for that patient
  post_samp <- postdf %>% 
    sample_n(size = N, replace = F)
  
  ret = pmap(post_samp, function(ba, bb, be, bf, br, am) {
    inv_logit( ba * lga_ + bb * lgb_ + be * lge_ +  bf * lgf_ + br * lgr_ + am ) 
  }) %>% 
    set_names(seq(1, N)) %>% 
    bind_rows() %>% 
    gather()
  return(ret)
}

# for the top quantile patients 
res_top <- pmap(ru_top, function(Akkermansia, Bacteroides, Enterococcus, Faecalibacterium, Ruminococcus){
  per_pt_sample_post_prob(Akkermansia, Bacteroides, Enterococcus, Faecalibacterium, Ruminococcus)
}) %>% 
  set_names(paste('P', seq(1, nrow(ru_top)), sep = '')) %>% 
  bind_rows(.id = 'pt')

# for the bottom quantile patients
res_bot <- pmap(ru_bot, function(Akkermansia, Bacteroides, Enterococcus, Faecalibacterium, Ruminococcus){
  per_pt_sample_post_prob(Akkermansia, Bacteroides, Enterococcus, Faecalibacterium, Ruminococcus)
}) %>% 
  set_names(paste('P', seq(1, nrow(ru_bot)), sep = '')) %>% 
  bind_rows(.id = 'pt')
```

```{r}
# plotting and visualizing
# visualizing each patient
res_top %>% 
  gghistogram(x = 'value', fill = 'pt', add_density = T,
              title = '100 sampled patients that had top 10% Ruminococcus relab',
              xlab = 'Probability of having CR d100', ylab = 'Probability density') +
  theme(legend.position = 'none')

 
# averaging over all the patients
res_top %>% 
  gghistogram(x = 'value', 
              #add_density = T,
              title = '100 sampled patients that had top 10% Ruminococcus relab',
              xlab = 'Probability of having CR d100', ylab = 'Probability density') +
  theme(legend.position = 'none')

mean(res_top$value)
```


```{r}
# visualizing each patient
res_bot %>% 
  gghistogram(x = 'value', fill = 'pt', add_density = T,
              title = '100 sampled patients that had bottom 10% Ruminococcus relab',
              xlab = 'Probability of having CR d100', ylab = 'Probability density') +
  theme(legend.position = 'none')

# averaging over all the patients
res_bot %>% 
  gghistogram(x = 'value', 
              #add_density = T,
              title = '100 sampled patients that had bottom 10% Ruminococcus relab',
              xlab = 'Probability of having CR d100', ylab = 'Probability density') +
  theme(legend.position = 'none')

mean(res_bot$value)
```

```{r}
# plot them together in one 
bind_rows(
  res_top %>% mutate(grp = 'top'),
  res_bot %>% mutate(grp = 'bot')
) %>% 
  gghistogram(x = 'value',bins = 30, fill = 'grp', palette = 'nejm', color = 'white', add = 'mean',
                  xlab = 'Predicted probability of CR d100', ylab = 'Probability density')+
  ggsave('../figs/predicted_CR_Ruminococcus_top_bottom_10.pdf', width = 7, height = 5)

bind_rows(
  res_top %>% mutate(grp = 'top'),
  res_bot %>% mutate(grp = 'bot')
)  %>% 
  group_by(grp) %>% 
  summarise(ave = mean(value))
```
