---
title: "16s lefse"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
```
 
```{r}
# sort out the asv counts table and also do filtering (need to have all taxa levels)
meta <- read_csv('../data/amplicon/stool/combined_2_meta.csv')

library(vdbR)
connect_database('~/dbConfig.txt')
get_table_from_database('asv_annotation_blast_ag')
cts <- get_counts_subset(meta$sampleid)

cts_ <- cts %>% 
  select(asv_key, sampleid, count_relative) %>% 
  spread(key = 'sampleid', value = 'count_relative', fill = 0) 

annot <- asv_annotation_blast_ag %>% 
  filter(asv_key %in% cts_$asv_key) %>% 
  mutate(ordr =  if_else(ordr == '', str_glue('of_class_{class}'), ordr),
         family =  if_else(family == '', str_glue('of_order_{ordr}'), family),
         genus =  if_else(genus == '', str_glue('of_family_{family}'), genus),
         species =  if_else(species == '', str_glue('of_genus_{genus}'), species)) %>% 
  mutate(taxa_asv = str_glue('k__{kingdom}|p__{phylum}|c__{class}|o__{ordr}|f__{family}|g__{genus}|s__{species}|a__{asv_key}'))

cts_all <- cts_ %>% 
  full_join(annot %>%  select(asv_key, taxa_asv), by  = 'asv_key') %>% 
  select(-asv_key)  %>% 
  gather('sampleid', 'relab', names(.)[1]:names(.)[ncol(.)-1]) %>% 
  left_join(meta %>% select(sampleid, cr_d100, toxicity), by = 'sampleid')


# the asv to keep
# keep the asvs that show up in at least 25% of the samples
keepg <- cts_all %>% 
  filter(relab > 0.0001) %>%
  ungroup() %>% 
  count(taxa_asv) %>% 
  filter(n > floor(nrow(meta) * 0.25)) %>% 
  pull(taxa_asv)
 
cts_fil <- cts_all %>% 
  filter(taxa_asv %in% keepg) %>% 
  spread('sampleid', 'relab', fill = 0)
```


```{r}
# the pheno label for the samples
pheno <- meta %>% 
  select(center, cr_d100:crs, icans, sampleid) %>% 
  gather('pheno', 'value', cr_d100:icans) 

all_sub_pheno <- pheno %>% 
  split(., list(.$pheno)) %>% 
  purrr::imap(~ filter(.data = ., value != 'not_assessed'))

tpheno <- all_sub_pheno %>% 
  imap(function(.x, .y){
    select(.data = .x, value) %>% 
      t() %>% write.table(str_glue('../data/amplicon/lefse/pull_{.y}.txt'), sep = '\t', quote = F, row.names = T, col.names = F)
  })

tcts <- all_sub_pheno %>% 
  map(~ pull(.data = ., sampleid) ) %>% 
  imap(~ cts_fil %>% select(taxa_asv, matches(.x)) %>%  write_tsv(str_glue('../data/amplicon/lefse/{.y}_asv_tcts.tsv'))) 
```



```{bash}
cat ../data/amplicon/lefse/pull_toxicity.txt ../data/amplicon/lefse/toxicity_asv_tcts.tsv > ../data/amplicon/lefse/pull_toxicity_asv_tcts.tsv
cat ../data/amplicon/lefse/pull_cr_d100.txt ../data/amplicon/lefse/cr_d100_asv_tcts.tsv > ../data/amplicon/lefse/pull_cr_d100_asv_tcts.tsv 
cat ../data/amplicon/lefse/pull_crs.txt ../data/amplicon/lefse/crs_asv_tcts.tsv > ../data/amplicon/lefse/pull_crs_asv_tcts.tsv
cat ../data/amplicon/lefse/pull_icans.txt ../data/amplicon/lefse/icans_asv_tcts.tsv > ../data/amplicon/lefse/pull_icans_asv_tcts.tsv
```


```{r}
fns <- list.files('../data/amplicon/lefse/', pattern = 'pull.*_asv_tcts.tsv$')

cmds <- tibble(
  fns = fns
) %>% 
  mutate(format_cmd = str_glue('format_input.py {fns}  {fns}.in -c 1  -u 2 -o 1000000   ')) %>% 
  mutate(run_cmd = str_glue('run_lefse.py {fns}.in  {fns}.res')) %>% 
  mutate(plot_cmd = str_glue('plot_res.py {fns}.res {fns}.pdf --format pdf  --feature_font_size 4 --width 10 --dpi 300 --title {fns}')) %>% 
  mutate(clado_cmd = str_glue('plot_cladogram.py {fns}.res {fns}_clado.pdf  --label_font_size 4 --dpi 300 --format pdf --title {fns}')) %>% 
  select(-fns) %>% 
  gather() %>% 
  select(value) %>% 
  write_csv('../data/amplicon/lefse/lefse_run_cmd_taxa.sh', col_names = F)
   

```

  
```{r}
# to see the relative abundance of those taxa 
# to get the top and bottom three taxa of the lefse results
res <- list.files('../data/amplicon/lefse/', pattern = 'asv_tcts.tsv.res$', full.names = T)

# gather the species level taxa in the lefse significant results
res_all <- res %>% 
  set_names(res) %>% 
  map(~ read_tsv(., col_names = c('feature','xx','direction','score','pval')) %>% 
        filter(!is.na(score))) %>% 
  keep(~ nrow(.) > 0) %>% 
  bind_rows(.id = 'res') %>% 
  mutate(res = str_replace(res, '^.+//',''),
         res = str_replace(res, '_asv.+$',''))  %>% 
  rename(grp = res) %>% 
  filter(grp %in% c('pull_cr_d100','pull_toxicity')) %>% 
  mutate(feature = str_replace_all(feature, '\\.','\\|')) %>% 
  #split(., list(.$grp, .$direction)) %>% 
  #map_dfr(~ top_n(x = ., n = 4, wt = score) %>% arrange(-score)) %>% 
  filter(str_detect(feature, 's__.+$')) %>% 
  filter(!str_detect(feature, 'a__.+$')) %>% 
  mutate(feature = str_replace(feature, '^.+s__','')) %>% 
  mutate(feature = str_replace(feature, '_Clostridium_', '[Clostridium]')) %>% 
  ungroup()


# plot the relab of those taxa (at species level) in boxplot
# get the species counts of the sampels
cts_spp <- cts_ %>% 
  full_join(annot %>%  select(asv_key, species), by  = 'asv_key') %>% 
  select(-asv_key)  %>% 
  gather('sampleid', 'relab', names(.)[1]:names(.)[ncol(.)-1]) %>% 
  group_by(sampleid, species) %>% 
  summarise(Relab = sum(relab)) %>% 
  select(sampleid, species, Relab) %>% 
  left_join(meta %>% select(sampleid, cr_d100, toxicity), by = 'sampleid') %>% 
  ungroup()

joined <- cts_spp %>% 
  inner_join(res_all, by = c('species' = 'feature'))

# finally I can do the plotting

joined  %>%
  filter(grp == 'pull_cr_d100') %>% 
  ggboxplot(x = 'cr_d100', y = 'Relab', add = 'jitter', title = 'Outcome: cr_d100') +
  facet_wrap(direction ~ species) +
  ggsave('../figs/amplicon/lefse_taxa_crd100.pdf', width = 15, height = 13)
 
```
  
```{r}
joined  %>%
  filter(grp == 'pull_toxicity') %>% 
  ggboxplot(x = 'toxicity', y = 'Relab', add = 'jitter', title = 'Outcome: toxicity') +
  facet_wrap(direction ~ species) +
  ggsave('../figs/amplicon/lefse_taxa_toxicity.pdf', width = 15, height = 13)
```

