---
title: "Comparisons in three center"
output: html_document
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

For Marcel's slides , including the 9 that were removed and do taxa lefse (2021-4-19)

```{r}
# UPDATE THIS TABLE BABY
cur <- read_csv('../data/shotgun_pheno/final_comprehensive.csv') %>% 
  select(fid, center, cr_d100, toxicity, icans, crs) %>% 
  filter(center != 'I') %>% # manually update the label for the "not_assessed"
  mutate(cr_d100 = case_when(
    fid == '2460A' ~ 'no',
    fid == '2293A' ~ 'no',
    fid == '2563A' ~ 'no',
    TRUE ~ cr_d100
  ))

pheno <- cur %>% 
  gather('pheno', 'value', cr_d100:crs) 
```


## run both of them with all of the samples pulled together

```{r}
all_sub_pheno <- pheno %>% 
  split(., list(.$pheno)) %>% 
  purrr::imap(~ filter(.data = ., value != 'not_assessed'))

all_sub_pheno %>% 
  imap(function(.x, .y){
    select(.data = .x, value) %>% 
      t() %>% 
      write.table(str_glue('../data/shotgun_output/humann3/pull_{.y}.txt'), sep = '\t', quote = F, row.names = T, col.names = F)
  })

```

## The taxa relative abundance from the shotgun data using metaphlan

```{r}
taxa <- read_tsv('../data/shotgun_output/metaphlan/merged_abundance_table.txt')  %>% 
  rename_all(funs(str_replace(., '_profile$','')))

all_tcts <- all_sub_pheno %>% 
  map(~ pull(.data = ., fid) ) %>% 
  imap(~ taxa %>% select(clade_name, matches(.x)) %>% 
         write_tsv(str_glue('../data/shotgun_output/humann3/pull_{.y}_tcts.tsv')))

# then just need to use the snakemake rule to cat the two
```

```{r}
# run lefse
fns <- list.files('../data/shotgun_output/humann3/', pattern = 'lefse_ready_tcts.tsv$')

cmds <- tibble(
  fns = fns
) %>% 
  mutate(format_cmd = str_glue('format_input.py {fns}  {fns}.in -c 1 -u 2 -o 1000000')) %>% 
  mutate(run_cmd = str_glue('run_lefse.py {fns}.in  {fns}.res')) %>% 
  mutate(plot_cmd = str_glue('plot_res.py {fns}.res {fns}.pdf --format pdf --feature_font_size 4 --width 10 --dpi 300 --title {fns}')) %>% 
  mutate(clado_cmd = str_glue('plot_cladogram.py {fns}.res {fns}_clado.pdf  --label_font_size 4 --dpi 300 --format pdf --title {fns}')) %>% 
  select(-fns) %>% 
  gather() %>% 
  select(value) %>% 
  write_csv('../data/shotgun_output/humann3/lefse_run_cmd_taxa.sh', col_names = F)
```

