---
title: "logistic regression"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F)
```

```{r}
library(magrittr)
library(ggeffects)
library(tidyverse)
library(lme4)
```

```{r}
meta <- read_csv('../data/amplicon/stool/combined_2_meta.csv') %>% 
  mutate(center = factor(center),
         toxicity = factor(toxicity, levels = c('no','yes')),
         cr_d100 = factor(cr_d100, levels = c('no','yes')))

dat <- meta %>% 
  select(toxicity,cr_d100, simpson_reciprocal, center)

dat %>% 
  head
```

# Alpha diversity as predictor

## Toxicity ~ alpha diversity + center

```{r}
m_tox <- glm(
  toxicity ~ simpson_reciprocal + center, 
  data = dat, 
  family = binomial(link = "logit")
)
summary(m_tox)

ggpredict(m_tox,se=TRUE,interactive=TRUE,digits=3, c('simpson_reciprocal','center')) %>% plot()
```

## CR ~ alpha diversity + center

```{r}
m_CR <- glm(
  cr_d100 ~ simpson_reciprocal + center, 
  data = dat, 
  family = binomial(link = "logit")
)
summary(m_CR)

ggpredict(m_CR,se=TRUE,interactive=TRUE,digits=3, c('simpson_reciprocal','center')) %>% plot()
```

# 5 genera as predictor

## Toxicity ~ Akkermansia + Bacteroides + Enterococcus + Faecalibacterium + Ruminococcus + center

```{r}
genera <- read_csv('../data/amplicon/stool/combined_5_genera.csv')

gmeta <- meta  %>% 
  inner_join(genera) %>% 
  select(toxicity,cr_d100, Akkermansia,Bacteroides, Enterococcus, Faecalibacterium, Ruminococcus , center)
```

```{r}
g_tox <- glm(
  toxicity ~ Akkermansia + Bacteroides + Enterococcus + Faecalibacterium + Ruminococcus + center, 
  data = gmeta, 
  family = binomial(link = "logit")
)
summary(g_tox)

ggpredict(g_tox,se=TRUE,interactive=TRUE,digits=3, c('Bacteroides','center')) %>% plot()
ggpredict(g_tox,se=TRUE,interactive=TRUE,digits=3, c('Ruminococcus','center')) %>% plot()
ggpredict(g_tox,se=TRUE,interactive=TRUE,digits=3, c('Enterococcus','center')) %>% plot()
ggpredict(g_tox,se=TRUE,interactive=TRUE,digits=3, c('Akkermansia','center')) %>% plot()
ggpredict(g_tox,se=TRUE,interactive=TRUE,digits=3, c('Faecalibacterium','center')) %>% plot()
```

## CR ~ Akkermansia + Bacteroides + Enterococcus + Faecalibacterium + Ruminococcus + center

```{r}
g_CR <- glm(
  cr_d100 ~ Akkermansia + Bacteroides + Enterococcus + Faecalibacterium + Ruminococcus + center, 
  data = gmeta, 
  family = binomial(link = "logit")
)
summary(g_CR)

ggpredict(g_CR,se=TRUE,interactive=TRUE,digits=3, c('Bacteroides','center')) %>% plot()
ggpredict(g_CR,se=TRUE,interactive=TRUE,digits=3, c('Ruminococcus','center')) %>% plot()
ggpredict(g_CR,se=TRUE,interactive=TRUE,digits=3, c('Enterococcus','center')) %>% plot()
ggpredict(g_CR,se=TRUE,interactive=TRUE,digits=3, c('Akkermansia','center')) %>% plot()
ggpredict(g_CR,se=TRUE,interactive=TRUE,digits=3, c('Faecalibacterium','center')) %>% plot()
```

