---
title: "Bayesian with CLR"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F)
```

```{r}
library(rethinking)
library(tidyverse)  
library(ggpubr)
set.seed(123)

```

```{r}
clr_5 <- read_csv('../data/amplicon/stool/counts_genus_combined_CLR.csv') %>% 
  spread(key = 'genus', value = 'clr') 

meta <- read_csv('../data/amplicon/stool/combined_2_meta_expanded.csv')  %>% 
  inner_join(clr_5) 
```

```{r}
dat_list <- list(
    tox = meta$tox,
    cr100 = meta$cr100,
    location = meta$loca,
    Akkermansia = meta$Akkermansia,
    Bacteroides = meta$Bacteroides,
    Enterococcus = meta$Enterococcus,
    Faecalibacterium = meta$Faecalibacterium,
    Ruminococcus = meta$Ruminococcus
    ) 
```

```{r}
gtox <- ulam(
    alist(
        tox ~ dbinom( 1 , p ) ,
        logit(p) <- ba*Akkermansia + bb*Bacteroides + be*Enterococcus + bf*Faecalibacterium + br*Ruminococcus  + a[location] ,
        ba ~ dnorm( 0 , 0.25),
        bb ~ dnorm( 0 , 0.25),
        be ~ dnorm( 0 , 0.25),
        bf ~ dnorm( 0 , 0.25),
        br ~ dnorm( 0 , 0.25),
        a[location] ~ dnorm( 0 , 0.5 )
    ) , data=dat_list , chains=4 , log_lik=TRUE , cores = 16)
precis(gtox, prob = 0.95)   
plot(precis(gtox, depth = 2, prob = 0.95) )   
# the  Ruminococcus looks more significant now
```

```{r}
# make this plot myself with a pre-defined range in the axis
df <- precis(gtox,  prob = 0.95)  %>% as.tibble()
df <- df %>%
  mutate(variable = c('Akkermansia', 'Bacteroides','Enterococcus','Faecalibacterium','Ruminococcus'))
#remove row number 1 (The intercept)
df %>% 
  ggplot(aes(x = variable, y = mean)) +
  geom_point(shape = 15,
             size  = 4, width = 0.1,
             position = "dodge", color="black") +
  geom_errorbar(aes(ymin  = `2.5%`,
                    ymax  = `97.5%`),
                width = 0.1,
                size  = 0.7,
                position = "dodge", color="turquoise4") +
  theme(axis.title = element_text(face = "bold")) +
  xlab("Variables") + ylab("Coefficient with 95% CI") +
  coord_flip(ylim = c(-1.5, 1.5)) +
  geom_hline(yintercept = 0, color = "red", size = 1) +
   theme(axis.title = element_text(size = 0)) +
  theme(axis.text = element_text(size = 14)) +
  labs(title = 'Toxicity') +
  ggsave('../figs/amplicon/bayesian_genera_tox_CLR.pdf', width = 5, height = 4)
```


```{r}
# maybe I can do a prior check with one real sample value for a test
prior <- extract.prior( gtox , n=1e4, cores = 16 )


# test sample values
test_dat <- clr_5 %>% 
  slice_sample(n = 1)

# make it into a function so that I can do the m and p the same time
# prior_tox <- list(m = 1, p = 2) %>% 
#   map(function(center_){
#     ret = inv_logit( prior$ba * test_dat$Akkermansia + prior$bb * test_dat$Bacteroides + prior$be * test_dat$Enterococcus +  prior$bf * test_dat$Faecalibacterium + prior$br * test_dat$Ruminococcus + prior$a[, center_] ) 
#     return(ret)
#   }) 

ret_m = inv_logit( prior$ba * test_dat$Akkermansia + prior$bb * test_dat$Bacteroides + prior$be * test_dat$Enterococcus +  prior$bf * test_dat$Faecalibacterium + prior$br * test_dat$Ruminococcus + prior$a[, 1] ) 

ret_p = inv_logit( prior$ba * test_dat$Akkermansia + prior$bb * test_dat$Bacteroides + prior$be * test_dat$Enterococcus +  prior$bf * test_dat$Faecalibacterium + prior$br * test_dat$Ruminococcus + prior$a[, 2] ) 
 

# the distribution of probability
tibble(m = ret_m, p = ret_p) %>% 
  gather() %>% 
  gghistogram(x  = 'value', fill = 'key')
# a little uneven 
```


```{r}
gcr <- ulam(
    alist(
        cr100 ~ dbinom( 1 , p ) ,
        logit(p) <- ba*Akkermansia + bb*Bacteroides + be*Enterococcus + bf*Faecalibacterium + br*Ruminococcus  + a[location] ,
        ba ~ dnorm( 0 , 0.25),
        bb ~ dnorm( 0 , 0.25),
        be ~ dnorm( 0 , 0.25),
        bf ~ dnorm( 0 , 0.25),
        br ~ dnorm( 0 , 0.25),
        a[location] ~ dnorm( 0 , 0.5 )
    ) , data=dat_list , chains=4 , log_lik=TRUE , cores = 8)
precis(gcr, prob = 0.95)
plot(precis(gcr, depth = 2, prob = 0.95) )
```
```{r}
# make this plot myself with a pre-defined range in the axis
df <- precis(gcr,  prob = 0.95)  %>% as.tibble()
df <- df %>%
  mutate(variable = c('Akkermansia', 'Bacteroides','Enterococcus','Faecalibacterium','Ruminococcus'))
#remove row number 1 (The intercept)
df %>% 
  ggplot(aes(x = variable, y = mean)) +
  geom_point(shape = 15,
             size  = 4, width = 0.1,
             position = "dodge", color="black") +
  geom_errorbar(aes(ymin  = `2.5%`,
                    ymax  = `97.5%`),
                width = 0.1,
                size  = 0.7,
                position = "dodge", color="turquoise4") +
  theme(axis.title = element_text(face = "bold")) +
  xlab("Variables") + ylab("Coefficient with 95% CI") +
  coord_flip(ylim = c(-1.5, 1.5)) +
  geom_hline(yintercept = 0, color = "red", size = 1) +
   theme(axis.title = element_text(size = 0)) +
  theme(axis.text = element_text(size = 14)) +
  labs(title = 'CR') +
  ggsave('../figs/amplicon/bayesian_genera_cr_CLR.pdf', width = 5, height = 4)

get_table_from_database('counts_ag')
```
