---
title: "lefse with shotgun taxa"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
simple <- read_csv('../data/shotgun_pheno/final_comprehensive_UPDATED_simple.csv')

pheno <- simple %>% 
  gather('pheno', 'value', cr_d100:crs) 

all_sub_pheno <- pheno %>% 
  split(., list(.$pheno)) %>% 
  purrr::imap(~ filter(.data = ., value != 'not_assessed'))

all_sub_pheno %>% 
  imap(function(.x, .y){
    select(.data = .x, value) %>% 
      t() %>% 
      write.table(str_glue('../data/shotgun_output/humann3/pull_{.y}.txt'), sep = '\t', quote = F, row.names = T, col.names = F)
  })
```

```{r}
taxa <- read_delim('../data/shotgun_output/metaphlan/merged_abundance_table_metaphlan3.txt', delim = '\t', skip = 1)  %>% 
  rename_all(funs(str_replace(., '_metaphlan3_profile$',''))) %>% 
  filter(str_detect(clade_name, 's__.+$')) %>% 
  select(- NCBI_tax_id) %>% 
  gather('sampleid', 'relab', names(.)[2]:names(.)[ncol(.)]) %>% 
  filter(sampleid %in% simple$fid)

cts <- read_delim('../data/shotgun_output/metaphlan/merged_abundance_table_metaphlan3.txt', delim = '\t', skip = 1)  %>% 
  rename_all(funs(str_replace(., '_metaphlan3_profile$',''))) %>% 
  #filter(str_detect(clade_name, 's__.+$')) %>% 
  select(- NCBI_tax_id)

keeptaxa <- taxa %>% 
  filter(relab > 0.0001) %>%
  ungroup() %>% 
  count(clade_name) %>% 
  filter(n > floor(nrow(simple) * 0.25)) %>% 
  pull(clade_name)

cts_fil <- taxa %>% 
  #filter(clade_name %in% keeptaxa) %>% 
  spread('sampleid', 'relab', fill = 0)
  
all_tcts <- all_sub_pheno %>% 
  map(~ pull(.data = ., fid) ) %>% 
  imap(~ cts %>% select(clade_name, matches(.x)) %>% 
         write_tsv(str_glue('../data/shotgun_output/humann3/pull_{.y}_tcts.tsv')))

```

```{bash}
cat ~/projects/CART_microbiome/data/shotgun_output/humann3/pull_toxicity.txt ~/projects/CART_microbiome/data/shotgun_output/humann3/pull_toxicity_tcts.tsv > ~/projects/CART_microbiome/data/shotgun_output/humann3/pull_toxicity_lefse_ready_tcts.tsv
cat ~/projects/CART_microbiome/data/shotgun_output/humann3/pull_cr_d100.txt ~/projects/CART_microbiome/data/shotgun_output/humann3/pull_cr_d100_tcts.tsv > ~/projects/CART_microbiome/data/shotgun_output/humann3/pull_cr_d100_lefse_ready_tcts.tsv
```

```{r}
# run lefse
fns <- list.files('../data/shotgun_output/humann3/', pattern = 'lefse_ready_tcts.tsv$')

cmds <- tibble(
  fns = fns
) %>% 
  mutate(format_cmd = str_glue('format_input.py {fns}  {fns}.in -c 1 -u 2 -o 1000000')) %>% 
  mutate(run_cmd = str_glue('run_lefse.py {fns}.in  {fns}.res')) %>% 
  mutate(plot_cmd = str_glue('plot_res.py {fns}.res {fns}.pdf --format pdf --feature_font_size 4 --width 10 --dpi 300 --title {fns}')) %>% 
  mutate(clado_cmd = str_glue('plot_cladogram.py {fns}.res {fns}_clado.pdf  --label_font_size 4 --dpi 300 --format pdf --title {fns}')) %>% 
  select(-fns) %>% 
  gather() %>% 
  select(value) %>% 
  write_csv('../data/shotgun_output/humann3/lefse_run_cmd_taxa.sh', col_names = F)

```