ln -s /home/daia1/my_workdir/samples/melody/1191V.fastq /home/daia1/my_workdir/samples/melody/WGS_1.fastq
ln -s /home/daia1/my_workdir/samples/melody/1388A.fastq /home/daia1/my_workdir/samples/melody/WGS_2.fastq
ln -s /home/daia1/my_workdir/samples/melody/1409B.fastq /home/daia1/my_workdir/samples/melody/WGS_3.fastq
ln -s /home/daia1/my_workdir/samples/melody/1652A.fastq /home/daia1/my_workdir/samples/melody/WGS_4.fastq
ln -s /home/daia1/my_workdir/samples/melody/1661A.fastq /home/daia1/my_workdir/samples/melody/WGS_5.fastq
ln -s /home/daia1/my_workdir/samples/melody/1779A.fastq /home/daia1/my_workdir/samples/melody/WGS_6.fastq
ln -s /home/daia1/my_workdir/samples/melody/1742A.fastq /home/daia1/my_workdir/samples/melody/WGS_7.fastq
ln -s /home/daia1/my_workdir/samples/melody/V0040A.fastq /home/daia1/my_workdir/samples/melody/WGS_8.fastq
ln -s /home/daia1/my_workdir/samples/melody/1765A.fastq /home/daia1/my_workdir/samples/melody/WGS_9.fastq
ln -s /home/daia1/my_workdir/samples/melody/1787A.fastq /home/daia1/my_workdir/samples/melody/WGS_10.fastq
ln -s /home/daia1/my_workdir/samples/melody/1715A.fastq /home/daia1/my_workdir/samples/melody/WGS_11.fastq
ln -s /home/daia1/my_workdir/samples/melody/1511N.fastq /home/daia1/my_workdir/samples/melody/WGS_12.fastq
ln -s /home/daia1/my_workdir/samples/melody/1783C.fastq /home/daia1/my_workdir/samples/melody/WGS_13.fastq
ln -s /home/daia1/my_workdir/samples/melody/1638A.fastq /home/daia1/my_workdir/samples/melody/WGS_14.fastq
ln -s /home/daia1/my_workdir/samples/melody/1508A.fastq /home/daia1/my_workdir/samples/melody/WGS_15.fastq
ln -s /home/daia1/my_workdir/samples/melody/1450A.fastq /home/daia1/my_workdir/samples/melody/WGS_16.fastq
ln -s /home/daia1/my_workdir/samples/melody/1559A.fastq /home/daia1/my_workdir/samples/melody/WGS_17.fastq
ln -s /home/daia1/my_workdir/samples/melody/1618A.fastq /home/daia1/my_workdir/samples/melody/WGS_18.fastq
ln -s /home/daia1/my_workdir/samples/melody/1487A.fastq /home/daia1/my_workdir/samples/melody/WGS_19.fastq
ln -s /home/daia1/my_workdir/samples/melody/1840A.fastq /home/daia1/my_workdir/samples/melody/WGS_20.fastq
ln -s /home/daia1/my_workdir/samples/melody/2031A.fastq /home/daia1/my_workdir/samples/melody/WGS_21.fastq
ln -s /home/daia1/my_workdir/samples/melody/2050A.fastq /home/daia1/my_workdir/samples/melody/WGS_22.fastq
ln -s /home/daia1/my_workdir/samples/melody/140.fastq /home/daia1/my_workdir/samples/melody/WGS_23.fastq
ln -s /home/daia1/my_workdir/samples/melody/2083A.fastq /home/daia1/my_workdir/samples/melody/WGS_24.fastq
ln -s /home/daia1/my_workdir/samples/melody/2098A.fastq /home/daia1/my_workdir/samples/melody/WGS_25.fastq
ln -s /home/daia1/my_workdir/samples/melody/171.fastq /home/daia1/my_workdir/samples/melody/WGS_26.fastq
ln -s /home/daia1/my_workdir/samples/melody/2152A.fastq /home/daia1/my_workdir/samples/melody/WGS_27.fastq
ln -s /home/daia1/my_workdir/samples/melody/1717B.fastq /home/daia1/my_workdir/samples/melody/WGS_28.fastq
ln -s /home/daia1/my_workdir/samples/melody/2190A.fastq /home/daia1/my_workdir/samples/melody/WGS_29.fastq
ln -s /home/daia1/my_workdir/samples/melody/2108A.fastq /home/daia1/my_workdir/samples/melody/WGS_30.fastq
ln -s /home/daia1/my_workdir/samples/melody/275G.fastq /home/daia1/my_workdir/samples/melody/WGS_31.fastq
ln -s /home/daia1/my_workdir/samples/melody/222.fastq /home/daia1/my_workdir/samples/melody/WGS_32.fastq
ln -s /home/daia1/my_workdir/samples/melody/244.fastq /home/daia1/my_workdir/samples/melody/WGS_33.fastq
