---
title: "Kate chronic samples"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggvenn)
source('~/MSK/work/microbiome_db/SQL/scripts/get_data_from_query_OTU.R')
```

### Select the target samples that go into this comparison  

**So the key is that first you filter on the samples that have shotgun data!!!! **
**And then select the ones that are the closest !!! so that you don't waste any shotgun data!!!!!**

```{r}
chronic <- get_data_from_query_OTU(0,'frozen_set_cgvhd_ag')

# how many we actually have shotgun
catalog <- read_csv('/Volumes/vandenBrinkLab/Angel_Dai/Full_human_shotgun_catalog/full_human_shotgun_catalog_updated.csv')

chronic_shot <- chronic %>% 
  inner_join(catalog, by = 'sampleid')
```

```{r}
# We care about 3 time periods:
# PreHCT: (day_relative_to_hct >= -30 & day_relative_to_hct <= -6)
# PeriHCT: (day_relative_to_hct >= 7 & day_relative_to_hct <= 21)
# PeriD100: (day_relative_to_hct >= 70 & day_relative_to_hct <= 130)
# 
# We selected only one sample per patient. In case of multiple samples for the same patient, we selected the first baseline sample for PreHCT (closest to day –30) 
# or the sample closest to day 14 or day 100 in case of PeriHCT and PeriD100.

period_list <- chronic_shot %>% 
  select(patient_id, sampleid, case_status, day_relative_to_hct, directory) %>% 
  mutate(period = case_when(
    day_relative_to_hct >= -30 & day_relative_to_hct <= -6 ~ 'PreHCT',
    day_relative_to_hct >= 7 & day_relative_to_hct <= 21 ~ 'PeriHCT',
    day_relative_to_hct >= 70 & day_relative_to_hct <= 130 ~ 'PeriD100'
  )) %>% 
  # keep the records that are in the above periods
  filter(!is.na(period)) %>% 
  split(.$period)

# now get the time difference between the actual time and the ideal date we emphasize on
period_diff <- bind_rows(
  period_list %>% 
    pluck('PreHCT') %>% 
    mutate(tdiff = abs(day_relative_to_hct - (-30))),
  period_list %>% 
    pluck('PeriHCT') %>% 
    mutate(tdiff = abs(day_relative_to_hct - (14))),
  period_list %>% 
    pluck('PeriD100') %>% 
    mutate(tdiff = abs(day_relative_to_hct - (100)))
)

# target samples 
target <- period_diff %>% 
  filter(period == 'PeriD100') %>% 
  group_by(patient_id) %>% 
  arrange(tdiff, .by_group = T) %>% 
  slice(1)  %>% 
  arrange(patient_id, tdiff, sampleid) %>% 
  distinct(sampleid, .keep_all = T)
       
target %>% 
  write_csv('../data/kate/final_p100_sample.csv')

```


```{r}
current <- read_csv('~/projects/MSS_pipeline-/output/current_240_sample_preprocessing_stats.csv') 

# how many we actually have 
length(intersect(target$sampleid, current$sampleid))


# how many need to be uploaded 
target %>% 
  filter(!sampleid %in% current$sampleid) %>% 
  select(directory) %>% 
  mutate(cmd = str_glue('rsync --progress --partial -avz {directory} daia1@lilac.mskcc.org:~/my_workdir/samples/kate')) %>% 
  ungroup() %>%
  select(cmd) %>%   
  write_csv('../data/upload_kate_43.sh', col_names = F)
```

### Create the pheno table and make sure the input two tables are correctly sorted

```{r}
pheno <- target  %>% 
  ungroup %>% 
  mutate(fid = str_extract(directory, 'Sample.+IGO'),
         fid = str_replace(fid, 'Sample_',''),
         fid = str_replace(fid, '_IGO',''))  %>% 
  select(sampleid, case_status, fid) 

# the cts table 
cts <- read_tsv('../data/kate/pwabun/humann2_final_out/humann2_pathabundance_cpm_unstratified.tsv') %>% 
  rename(sampleid = names(.)[1]) %>% 
  rename_all(funs(str_replace(., '_Abundance$',''))) 
cts <- bind_cols(cts[,1],cts[,pheno$fid])


cts %>% 
  write_tsv('../data/kate/input_lefse_cts.tsv')


pheno_col <- pheno %>% 
  select(case_status) %>% 
  t %>% 
  write.table('../data/kate/input_lefse_pheno.txt', sep = '\t', quote = F, row.names = T, col.names = F)
 
```

